### ISSUE TITLE
As a user, I want to click on a Switch List button to access a different list

### ISSUE THREAD

**Issue by shahx95** [the-collab-lab/tcl-60-smart-shopping-list#42]
As a user, I want to have a "Switch List" link available in the navigation menu. When I click on this link, it should clear the token stored in the local storage. After clearing the token, the page should redirect me to the home page. On the home page, I should be presented with an option to enter a different token to log in. This will allow me to easily switch between different tokens.

# Acceptance Criteria
- [ ] The "Switch Token" link should be displayed in the navigation menu.
- [ ] Clicking on the "Switch Token" link should trigger an action to clear the token stored in the local storage.
- [ ] After clearing the token, the page should automatically redirect the user to the home page.

**Comment by labrocadabro** [comment]
I'd recommend calling it "switch list" instead. It's not a major issue but it's a little less mental friction.
